# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 504002c7ad22f893b630fa4eaff7e8040f5469ded3119650529d67c1425c77de6850437ade5df0f05aa94ff75936f6d6ec48a03bab0ea8ac372826dd5fb04e96

test:
  secret_key_base: c41548653def6197b3b0a37cdea555ef2ab59b3d2e11df517ed9ee875659e071483fcec775cbf275aa7b01e81b9a40e7cca833ac049194125970d1a93c5c7f6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
